### ISSUE TITLE
Enhance edit table nested grid - identiation level

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/mongo-modeler#59]
When we edit table, every time we click on a collapse field a new grid will be created and it will be shown nested (bumped) just to let the user know that is a nested object.

Right now they way we are building this layout is a bit clunky, we've got all this CSS classes:

_./src/pods/edit-table/edit-table.module.css_

```css
.indent0 {
  margin-left: 0;
}
.indent1 {
  margin-left: 20px;
}
.indent2 {
  margin-left: 40px;
}
.indent3 {
  margin-left: 60px;
}
.indent4 {
  margin-left: 80px;
}
.indent5 {
  margin-left: 100px;
}
.indent6 {
  margin-left: 120px;
}
.indent7 {
  margin-left: 140px;
}
```

And this code to apply the class depending on the indentation level :

_./src/pods/edit-table/components/nested-field-grid.tsx_

```tsx
export const NestedFieldGrid: React.FC<NestedFieldGridProps> = ({
  fields,
  level,
  expandedFields,
  toggleExpand,
  updateFieldValue,
}) => {
  const renderFieldHeaders = () => (
    <div className={`${classes.fieldRow} ${classes[`indent${level}`]}`}>
      <div className={`${classes.headerCell} ${classes.expandCell}`}>
        Expand
      </div>
      <div className={classes.headerCell}>PK</div>
      <div className={classes.headerCell}>FK</div>
      <div className={classes.headerCell}>Name</div>
      <div className={classes.headerCell}>Type</div>
    </div>
  );

  const renderField = (field: FieldVm): JSX.Element => (
    <React.Fragment key={field.id}>
      <div className={`${classes.fieldRow} ${classes[`indent${level}`]}`}>
```

Pay special attention to:

```tsx
    <div className={`${classes.fieldRow} ${classes[`indent${level}`]}`}>
```

```tsx
<div className={`${classes.fieldRow} ${classes[`indent${level}`]}`}>
```

We should remove the class and add some dynamic style in react multiplying the level by 20.
